### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Kreytal** [PiotrTe/OOP-Assignment-1#3]
-In my point of view, the comments in your program are explaining well of how your code works and what actions code supposed to do throughout all classes of the program. I don't see any issues with documentation in your project.

-Considering that all functionality was implemented as required and is working as intended, however I think you could have implemented it a bit different in some instances.

-I think you could use actual user input to determine the amount of cards your method is supposed to deal instead of just using number 5, it could improve the testing process, in range for example, as you wouldn't need to change the code every time you test it.
https://github.com/PiotrTe/OOP-Assignment-1/blob/3ae7800a274ba649012242697412c58f242e53f7/Testing.cs#L38-L41

-Other than that, you could make Validation.cs abstract, as it doesn't have a constructor and could be easily inherited by other classes. 
https://github.com/PiotrTe/OOP-Assignment-1/blob/3ae7800a274ba649012242697412c58f242e53f7/Validation.cs#L10

-Throughout testing the functionality of your validation, I could not find any issues or errors that would crash/shut down your program, as it validates input type and range perfectly, whereas I don't think there could be any more validation methos to handle this type of program.

-As mentioned above, you could improve your code by making Validation class an abstract class and remaking the second option of dealing cards by amount so the user of the program can input the amount of cards he would like to deal.

**Comment by PiotrTe** [comment]
Thanks for the feedback, using validation as a abstract class is a great idea, and allowing testers to choose the amount of cards they want to draw will make it a bit easier to test
